"""
Django settings for anhomaw project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lk1bi+trvz_(3dl)c_r2$9y4o6663tm@x!+f$!6t=)60@9-l(-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'user',
    'asb',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

# CORS_ORIGIN_WHITELIST= ["*"]

ROOT_URLCONF = 'anhomaw.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'anhomaw.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        #  'ENGINE': 'django.db.backends.sqlite3',
        #  'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'anhomaw',
        'USER': 'dujingxi',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'OPTIONS': {
            'init_command': 'SET sql_mode="STRICT_TRANS_TABLES"',
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ['anhomaw.util.authentications.MyTokenAuthentication'],    # 应用的认证列表
    "DEFAULT_AUTHENTICATION_TOKEN_EXPIRE": 86400, # token 过期时间，以秒为单位


    "DEFAULT_PERMISSION_CLASSES": ['anhomaw.util.permissions.MyCommonPermission'],     # 应用的权限列表
    "DEFAULT_PARSASSES": ['rest_framework.parsers.JSONParser', ],    # 应用的解析器列表 parser
# from rest_framework.parsers import JSONParser

    "DEFAULT_THROTTLE_CLASSES": ['anhomaw.util.throttles.MyDefaultThrottle'],  # 应用的节流／控制访问频率
    "DEFAULT_THROTTLE_RATES": {'default': '3/s', 'database': '30/m'},

    "UNAUTHENTICATED_USER": None,
    "UNAUTHENTICATED_TOKEN": None,

    "DEFAULT_PAGINATION_CLASS": "anhomaw.util.paginations.MyNumberPagination",
    # "DEFAULT_PAGINATION_CLASS": "anhomaw.util.paginations.MyCursorPagination",
    "PAGE_SIZE": 2,

    # version
    # "DEFAULT_VERSIONING_CLASS": 'rest_framework.versioning.URLPathVersioning',
    # "DEFAULT_VERSION": "v1",
    # "ALLOWED_VERSIONS": ["v1"],
    # "VERSION_PARAM": "version",
}
